version: '3.8'

services:
  web:
    image: cashogomez/tracybe:latest
    restart: always
    #command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn tracy_be.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: