# Generated by Django 5.0 on 2024-06-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='empresa_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='materno',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numeroEmpleado',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='paterno',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puesto',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
