# Generated by Django 5.0 on 2024-01-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiPerfilManager',
        ),
    ]
