# Generated by Django 5.0 on 2024-03-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_perfil_numeroempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.CharField(default='', max_length=500),
        ),
    ]
