# Generated by Django 5.0 on 2024-06-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0007_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='area',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puesto',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
