# Generated by Django 5.0 on 2024-03-30 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='set',
        ),
        migrations.AddField(
            model_name='ticket',
            name='anestesia',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='diagnostico',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='edad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_nacimiento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='habitacion',
            field=models.IntegerField(blank='', default=0, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='registro',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='anestesiologo',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='area_registro',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cirujano',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='enfermero',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fecha_cirugia',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='paciente',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='residente',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sala',
            field=models.IntegerField(blank='', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicita',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='turno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
