# Generated by Django 5.0 on 2024-01-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='ciclo',
        ),
        migrations.AddField(
            model_name='equipo',
            name='ciclos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='tracybe_app.ciclo'),
        ),
    ]
