# Generated by Django 5.0 on 2024-03-01 07:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0002_remove_equipo_ciclo_equipo_ciclos'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='caducidad',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='clasificacion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='foto',
            field=models.URLField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='codigo_qr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
