# Generated by Django 5.0 on 2024-06-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0002_ticketoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketoa',
            name='entrega_usuario',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ticketoa',
            name='recepcion_usuario',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
