# Generated by Django 5.0 on 2024-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0002_remove_ticket_instrumento_remove_ticket_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estatus',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
