# Generated by Django 5.0 on 2024-04-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0003_ticket_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracybe_app.instrumento')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracybe_app.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='SetTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracybe_app.set')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracybe_app.ticket')),
            ],
        ),
    ]
