# Generated by Django 5.0 on 2024-06-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0003_alter_ticketoa_entrega_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketoa',
            name='estatus',
            field=models.CharField(blank=True, default='', max_length=900, null=True),
        ),
    ]
