# Generated by Django 5.0 on 2024-03-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0003_instrumento_caducidad_instrumento_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='codigo_qr',
        ),
        migrations.CreateModel(
            name='Codigo_qr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('uso', models.IntegerField(blank=True, default=0, null=True)),
                ('valor', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('valido', models.BooleanField(blank=True, default=True, null=True)),
                ('empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listaempaquecodigo', to='tracybe_app.empaque')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listainstrumentocodigo', to='tracybe_app.instrumento')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listasetcodigo', to='tracybe_app.set')),
            ],
        ),
    ]
