# Generated by Django 5.0 on 2024-03-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0004_remove_instrumento_codigo_qr_codigo_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
