# Generated by Django 5.0 on 2024-04-19 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0004_instrumentoticket_setticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentoticket',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.instrumento'),
        ),
        migrations.AlterField(
            model_name='instrumentoticket',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.ticket'),
        ),
        migrations.AlterField(
            model_name='setticket',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.set'),
        ),
        migrations.AlterField(
            model_name='setticket',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='anestesia',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
