# Generated by Django 5.0 on 2024-06-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0005_setticketoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setticketoa',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.ticketoa'),
        ),
    ]
