# Generated by Django 5.0 on 2024-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0005_remove_instrumento_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='codigo_qr',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='uso',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='caducidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Codigo_qr',
        ),
    ]
