# Generated by Django 5.0 on 2024-04-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0005_alter_instrumentoticket_instrumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='tickets',
            field=models.ManyToManyField(through='tracybe_app.InstrumentoTicket', to='tracybe_app.ticket'),
        ),
        migrations.AddField(
            model_name='set',
            name='tickets',
            field=models.ManyToManyField(through='tracybe_app.SetTicket', to='tracybe_app.ticket'),
        ),
        migrations.AlterField(
            model_name='instrumentoempaque',
            name='empaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.empaque'),
        ),
        migrations.AlterField(
            model_name='instrumentoempaque',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.instrumento'),
        ),
        migrations.AlterField(
            model_name='instrumentoset',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.instrumento'),
        ),
        migrations.AlterField(
            model_name='instrumentoset',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.set'),
        ),
        migrations.AlterField(
            model_name='setempaque',
            name='empaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.empaque'),
        ),
        migrations.AlterField(
            model_name='setempaque',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracybe_app.set'),
        ),
    ]
