# Generated by Django 5.0 on 2024-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0006_alter_setticketoa_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketoa',
            name='devolucion_usuario',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ticketoa',
            name='recepcion_usuario_recepcion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
