# Generated by Django 5.0 on 2024-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0006_instrumento_tickets_set_tickets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='habitacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sala',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
