# Generated by Django 5.0 on 2024-03-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0006_remove_instrumento_cantidad_instrumento_codigo_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
