# Generated by Django 5.0 on 2024-03-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0007_instrumento_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='familia',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='individuo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
