# Generated by Django 5.0 on 2024-04-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0007_alter_ticket_habitacion_alter_ticket_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('marca', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tiempo_vida', models.IntegerField(blank=True, default=0, null=True)),
                ('unidad', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
