# Generated by Django 5.0 on 2024-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0007_ticketoa_devolucion_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setticketoa',
            name='cantidad_recibida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
