# Generated by Django 5.0 on 2024-06-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0008_setticketoa_cantidad_recibida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setticketoa',
            name='cantidad_recibida',
        ),
        migrations.AddField(
            model_name='instrumentoset',
            name='cantidad_recibida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
