# Generated by Django 5.0 on 2024-03-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0008_instrumento_familia_instrumento_individuo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='empaque',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='set',
        ),
        migrations.RemoveField(
            model_name='set',
            name='empaque',
        ),
        migrations.AddField(
            model_name='set',
            name='maximo',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='minimo',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='cantidadInstrumentos',
            fields=[
                ('instrumento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracybe_app.instrumento')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listaempaquecantidadinstrumento', to='tracybe_app.empaque')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listasetcantidadinstrumento', to='tracybe_app.set')),
            ],
        ),
        migrations.CreateModel(
            name='cantidadSet',
            fields=[
                ('set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracybe_app.set')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True)),
                ('empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listaempaquecantidadset', to='tracybe_app.empaque')),
            ],
        ),
    ]
