# Generated by Django 5.0 on 2024-04-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0009_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='id',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracybe_app.set'),
        ),
    ]
