# Generated by Django 5.0 on 2024-07-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0009_remove_setticketoa_cantidad_recibida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setticket',
            name='entregados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
