# Generated by Django 5.0 on 2024-04-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0010_remove_almacen_id_alter_almacen_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
