# Generated by Django 5.0 on 2024-04-25 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0011_almacen_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Almacen',
        ),
    ]
