# Generated by Django 5.0 on 2024-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0011_ticket_devolucion_usuario_ticket_entrega_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('fecha', models.DateTimeField(blank=True, default='', max_length=250, null=True)),
                ('usuario', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('incidencia', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('comentario', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
    ]
