# Generated by Django 5.0 on 2024-04-28 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0012_delete_almacen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empaque',
            name='caducidad',
        ),
        migrations.RemoveField(
            model_name='empaque',
            name='caracteristica',
        ),
        migrations.RemoveField(
            model_name='empaque',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='empaque',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='empaque',
            name='tipo',
        ),
        migrations.AddField(
            model_name='empaque',
            name='realizados',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='materialempaque',
            name='empaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracybe_app.empaque', unique=True),
        ),
    ]
