# Generated by Django 5.0 on 2024-04-28 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0013_remove_empaque_caducidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialempaque',
            name='empaque',
        ),
        migrations.AddField(
            model_name='empaque',
            name='materialempaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracybe_app.materialempaque', unique=True),
        ),
    ]
