# Generated by Django 5.0 on 2024-04-29 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0014_remove_materialempaque_empaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaque',
            name='materialempaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_empaque', to='tracybe_app.materialempaque', unique=True),
        ),
    ]
