# Generated by Django 5.0 on 2024-05-05 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0016_remove_instrumento_empaques_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaque',
            name='materialempaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_empaque', to='tracybe_app.materialempaque'),
        ),
    ]
