# Generated by Django 5.0 on 2024-05-06 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0017_alter_empaque_materialempaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empaque',
            name='materialempaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materialempaque', to='tracybe_app.materialempaque'),
        ),
    ]
