# Generated by Django 5.0 on 2024-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0019_remove_equipo_ciclos_ciclosequipo_ciclo_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='tipoequipo',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='equipos',
        ),
        migrations.AddField(
            model_name='equipo',
            name='ciclos',
            field=models.ManyToManyField(through='tracybe_app.CiclosEquipo', to='tracybe_app.ciclo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='TipoEquipo',
        ),
    ]
