# Generated by Django 5.0 on 2024-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracybe_app', '0020_remove_equipo_tipoequipo_remove_ciclo_equipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='estatus',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
